[theme]
font = "sans serif"

[theme.light]
primaryColor = "#2563EB"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"

[theme.dark]
primaryColor = "#3B82F6"
backgroundColor = "#0B0F19"
secondaryBackgroundColor = "#1E293B"
textColor = "#F8FAFC"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
